version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash /app/docker/entrypoint.sh && python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5439:5432"